source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SKSink' do
    pod 'TwistedOakCollapsingFutures'
    pod 'FMDB'
end

target 'SKSinkTests', :exclusive => true do
  pod "SKSink", :path => "../"

  
end
